version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/var/mysql:/var/lib/mysql
      - ./docker/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "${PROJ_NAME}_db"
      MYSQL_USER: "${PROJ_NAME}_user"
      MYSQL_PASSWORD: "123"
  php:
    image: php8.1:latest
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - php


volumes:
  mysql:
    driver: local